Add patch for YAML in instances of RUBY 3 or greater
acima-credit/tiki_torch pull request #12
Opened 2022-11-09 21:26 UTC by ajmyers01

2022-11-09 21:32 UTC, aemadrid commented
This seems safe enough on a short review. But it seems like it could explode for somebody using a class other than `[OpenStruct, Symbol, Time]` right? I'm tempted to let it merge but it seems we should have a big warning in the README and even specs that proves it will fail and how if you use something else. Maybe we should have a way to configure what classes are allowed?

In the end the solution is to replace SQS with Kafka and then having Avro replacing YAML for serialization. but until then I think we need to warn people from blindly migrating to Ruby 3.x and blowing up.

2022-11-09 21:32 UTC, aemadrid requested changes
See my comment on dealing with unexpected consequences.

2022-11-09 21:37 UTC, ajmyers01 commented
@aemadrid  In ruby 3, the .load is automatically safe_load
https://ruby-doc.org/stdlib-3.1.1/libdoc/psych/rdoc/Psych.html#method-c-safe_load
So there are a lot of classes on by default, this just expands that list. Are there any others you want me to include with this, I've only included the ones that are used in our fraud detector tests?

2022-11-09 21:40 UTC, aemadrid commented
@ajmyers01 what I mean is that each app, MP, VB, etc., might be serializing different classes. You'd hope everyone is using primitives but I'm sure someone else is. So by making the list configurable each app can update their own list to stay safe. Does that make sense? We can continue in Slack if it helps.

2022-11-09 21:43 UTC, ajmyers01 commented
@aemadrid  The errors are very loud in our tests when upgrading to ruby 3, I was just intending on adding them as I run into them.

2022-11-09 21:47 UTC, bfreese commented
Yea, I think if we document what is currently supported we can revise the gem to support other types if needed.  We could also just leave this in a branch for now until we get further down the path of upgrading other projects.  I would hate to put too much effort in given that this ultimately will be transitionary while we migrate from SQS.  Thoughts @aemadrid?

2022-11-09 21:50 UTC, ajmyers01 commented
TrueClass
FalseClass
NilClass
Integer
Float
String
Array
Hash

As can be found in that link I posted above  ☝️

2022-11-10 15:17 UTC, aemadrid approved these changes

2022-11-10 15:18 UTC, aemadrid commented
That should work, thanks!

2022-11-10 15:51 UTC, rlasch approved these changes
LGTM

2022-11-10 16:21 UTC, merged